_wandb:
    value:
        cli_version: 0.25.0
        e:
            19qt4v9c1vu0k6lgmohwu9w40s4xvs3o:
                args:
                    - --exp
                    - attention_rollout
                    - --model_path
                    - checkpoints/best_model.pt
                codePath: ablations.py
                codePathLocal: ablations.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "391247818752"
                        used: "289942753280"
                email: ma25m024@smail.iitm.ac.in
                executable: C:\Users\SAGNIK BARMAN\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: bca24bfe4215463265dc7f72d9416f449e2ad4c6
                    remote: https://github.com/Sagnik-Barman/DA6401-Assignment-3.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-67b527b3-4672-3c72-dfef-7aedde5b2cb5
                host: DESKTOP-HKBG4RS
                memory:
                    total: "24823836672"
                os: Windows-11-10.0.26200-SP0
                program: D:\Frameworks\DA6401-Assignment-3\ablations.py
                python: CPython 3.13.5
                root: D:\Frameworks\DA6401-Assignment-3
                startedAt: "2026-05-12T21:00:17.057995Z"
                writerId: 19qt4v9c1vu0k6lgmohwu9w40s4xvs3o
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 33
                - 49
                - 51
            "2":
                - 1
                - 33
                - 49
                - 51
            "3":
                - 13
            "4": 3.13.5
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
